### ISSUE TITLE
Crash : securityException  : Unable to start service

### ISSUE THREAD

**Issue by GaelCougnaud** [ezeeworld/B4S-Android-SDK#7]
Hi,

We have just published an update of our app, that integrates B4S SDK 1.8.4.
In our app, we use "Crashlytics" to obtain user crashs.
In one day, an user meet a same crash 25 times.

Trace :
Fatal Exception: java.lang.SecurityException: Unable to start service Intent { act=com.ezeeworld.b4s.android.sdk.monitor.B4S_QUERY_VERSION cmp=com.ezeeworld.qelmc/com.ezeeworld.b4s.android.sdk.monitor.MonitoringManager (has extras) }: Unable to launch app com.ezeeworld.qelmc/10145 for service Intent { act=com.ezeeworld.b4s.android.sdk.monitor.B4S_QUERY_VERSION cmp=com.ezeeworld.qelmc/com.ezeeworld.b4s.android.sdk.monitor.MonitoringManager }: com.ezeeworld.qelmc is restricted
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1760)
       at android.app.ContextImpl.startService(ContextImpl.java:1733)
       at android.content.ContextWrapper.startService(ContextWrapper.java:515)
       at com.ezeeworld.b4s.android.sdk.monitor.MonitoringManager.onHandleIntent(SourceFile:120)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
NB : Line numbers could be not the good ones       

This user have got a TCL 604yL device (Alcatel one Touch 3.2.5 LTE) with android 5.0.2.  
His phone is not rooted.
That sounds be a device's blocking. Perhaps the user have an anti-virus.

Could you add a fix or catch the problem to avoid a crash ?

Best regards,
Gaël

**Comment by kris92** [comment]
Hello Gaël,

Thank you for you report. Can you give us your B4S ApplicationId. So we will attempt to identify the user and find a workaround for this problem.

Regards,

Christophe

**Comment by GaelCougnaud** [comment]
I suppose "B4S Application Id" is a confidential data.
Could you give me an email to I can send you this information ?

**Comment by freboursier-ez** [comment]
Hello Gael,

You can send me the application ID to francois.reboursier@ezeeworld.com
