### ISSUE TITLE
Crash : AsyncExecutor: de.greenrobot.event.util.AsyncExecutor.execute

### ISSUE THREAD

**Issue by GaelCougnaud** [ezeeworld/B4S-Android-SDK#9]
Bonjour,

Depuis que nous avons intégré votre SDK (version 1.8.4), nous avons des remontées de crash de notre application, dû à un excès de threads existants à un instant t. Cela entraîne un OutOfMemoryError. CE crash peut même survenir quand l'application est arrêtée. Dans les traces d'erreurs, nous voyons qu'il y a énormément de threads créés par votre SDK (> 900 threads).
Je pense qu'il doit avoir un problème de threads à durée infinie.

Trace du crash : 
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
       at de.greenrobot.event.util.AsyncExecutor.execute(SourceFile:111)
       at com.ezeeworld.b4s.android.sdk.monitor.InteractionService.onStartCommand(SourceFile:122)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2845)
       at android.app.ActivityThread.access$2100(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5350)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java) 

La trace des threads actifs est la suivante :
pool-14-thread-695
       at com.ezeeworld.b4s.android.sdk.monitor.e.a(SourceFile:89)
       at com.ezeeworld.b4s.android.sdk.monitor.InteractionService$4.run(SourceFile:129)
       at de.greenrobot.event.util.AsyncExecutor$1.run(SourceFile:115)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Cordialement,
Gaël

**Comment by kris92** [comment]
This issue will be fixed on our next release 2.0.1 scheduled for Jul, 21
